### PR TITLE
[BUGFIX] Daily logrotate

### PR DESCRIPTION
**Pull request by StephenKing**

### CODE REVIEW

**Review by stucki — APPROVED** [review]

**Comment by stucki** [comment]
@StephenKing Any idea why the tests have failed?

**Comment by StephenKing** [comment]
Yes, testing against external / production servers is a bad idea (as we all know):

https://github.com/TYPO3-cookbooks/site-proxytypo3org/blob/0aa7e4d5405ebde2cf5cfef8f370cb22cf1cb497/test/integration/data_bags/proxy/typo3_org.json#L5

**Comment by StephenKing** [comment]
okay to merge for me, once tests passed

**Comment by stucki** [comment]
@StephenKing Thank you! :+1:

**Pull request merged**
